### PR TITLE
Pod4 Motion Model improvements and tests

### PR DESCRIPTION
**Pull request by rgw3d**
Updated how MotionModel.cpp process Position/ Velocity/ Acceleration. Please give me feedback on this!

Also added in a bunch of tests for the Motion Model code. Nothing very complicated or realistic, but enough to verify that things work as expected.

### CODE REVIEW

**Review by epaglier — COMMENTED** [review]
I like all of the changes! The low pass filter is a good way to address potentially dirty data! In the future are you wanting to dynamically adjust the lowpass_percent or determine a value and leave it at that? Also is the intention of the lowpass filter to not fully trust our new sensor value? Could this lead to an underestimation of velocity and are we ok with that, also would it compound over time? I am going to sleep now but I will review the motion tests in the morning and approve the merge.

**Comment by rgw3d** [comment]
> I like all of the changes! The low pass filter is a good way to address potentially dirty data! In the future are you wanting to dynamically adjust the lowpass_percent or determine a value and leave it at that? Also is the intention of the lowpass filter to not fully trust our new sensor value? Could this lead to an underestimation of velocity and are we ok with that, also would it compound over time? I am going to sleep now but I will review the motion tests in the morning and approve the merge.

I agree that the lowpass filter isn't perfect, but it should help to remove some high-frequency noise. Though we need to do testing to determine if there even is high-frequency noise! 

Remember that the lowpass filter is literally just a weighted average of the previous value and the new value. The "alpha" value (as I have seen it in literature) is the percent. Like do you take 90% of the old value and only 10% of the new value? Another really important note is how frequently this filter is called, because the more frequently it is called (along with a high alpha value) the more it will smooth out the high-frequency spikes while converging quickly to the desired value

**Comment by epaglier** [comment]
> > I like all of the changes! The low pass filter is a good way to address potentially dirty data! In the future are you wanting to dynamically adjust the lowpass_percent or determine a value and leave it at that? Also is the intention of the lowpass filter to not fully trust our new sensor value? Could this lead to an underestimation of velocity and are we ok with that, also would it compound over time? I am going to sleep now but I will review the motion tests in the morning and approve the merge.
> 
> I agree that the lowpass filter isn't perfect, but it should help to remove some high-frequency noise. Though we need to do testing to determine if there even is high-frequency noise!
> 
> Remember that the lowpass filter is literally just a weighted average of the previous value and the new value. The "alpha" value (as I have seen it in literature) is the percent. Like do you take 90% of the old value and only 10% of the new value? Another really important note is how frequently this filter is called, because the more frequently it is called (along with a high alpha value) the more it will smooth out the high-frequency spikes while converging quickly to the desired value

Just for my understanding, would the low pass filter be able to converge to a value when the velocity is changing?

**Comment by rgw3d** [comment]
> Just for my understanding, would the low pass filter be able to converge to a value when the velocity is changing?

Short answer: No. Longer answer, kinda.

For example, if velocity sensor value is updated once per second, thus the filter is called once per second, then the output from the filter will lag behind the sensor value. This is OK when sensor value is consistent, but not great when you know the sensor value is increasing (e.g. you are accelerating). 

`filter_output = low_pass(filter_output, sensor_value, 0.90)`
which expands to:
`filter_output = filter_output*0.9 + sensor_value*0.1`
The `filter_output` would converge to the `sensor_value` given `sensor_value` never changes on every update.

So the question is: How noisy is our sensor input? If our sensor input is perfect, there is no need for a filter. If our sensor data does produce some high frequency spikes, for example:
v = 1, 2, 3, 4, 5, **9,** 7, 8, 9, 10, **7,** 12, 13, 14 and so on...
Then a low pass filter would help to smooth those out. it is really a matter of choosing the `alpha` value (in the example it was 0.9)

**Review by epaglier — APPROVED** [review]
Looks good! We just need to check the values we get to see how much of the low pass filter we need to use.

**Pull request merged**
