### PR TITLE
Welp I tried

### PR DESCRIPTION
**Pull request by AFederici**
I missed last meeting so I wasn't super sure what to do but I dug around the code a little bit and gave it a shot

### CODE REVIEW

**Comment by schmidtwmark** [comment]
Your code does not compile

**Comment by schmidtwmark** [comment]
I saw your new commit, it still doesn't compile. Checkout line 27 in tests/StateTest.cpp.

Once your code compiles, I'll add you to slack and give you more feedback

**Comment by schmidtwmark** [comment]
It compiles, but PodTest.Accelerate does not pass. Why is that?

**Comment by AFederici** [comment]
Accelerate should work now, I incorrectly allowed the pod back into safe mode from that state

**Pull request closed without merging**
