### PR TITLE
Added another test for testing emergency brakes.

### PR DESCRIPTION
**Pull request by rishiwadhwa0**
Added another test for emergency brake testing to the automatic test file. Will add more tests soon as more ideas come to mind.

### CODE REVIEW

**Review by anshulshah957 — COMMENTED** [review]
The first commit is good. Add an expect true for the brakes being enabled, as that also is supposed to happen when the emergency brakes are activated. Works locally and on bbb.

**Review by anshulshah957 — DISMISSED** [review]
This second commit doesn't work. After the move to the emergency brake state, waiting for a transition to coast causes the test to wait forever. Furthermore, the functionality for the automatic transition from brake to safe mode is not in place yet, so that test will fail right now. Also, if that test were to be implemented in the future, it should be done so in a seperate unit test.

**Comment by rgw3d** [comment]
Let's get this to the point where all of your tests pass all of the time. You might need to modify how the Simulator.cpp calculates acceleration / velocity in order to prevent the problems where the test never finish. Since we don't set the "pressure" variable, braking doesn't do anything to the kinematics. I suggest changing this!

**Comment by rgw3d** [comment]
Anywhere from 5 to 10 tests fail depending on the run!

**Review by rgw3d — APPROVED** [review]
Looks good now

**Pull request merged**
