### PR TITLE
StateTest.cpp attempt

### PR DESCRIPTION
**Pull request by benoiteom**

### CODE REVIEW

**Comment by schmidtwmark** [comment]
Your code does not compile! Once it compiles, I'll give more feedback and add you to slack.

**Comment by schmidtwmark** [comment]
Still does not compile. Make sure you run "make." If you see "Success" you know it compiled successfully. Your problem is with the Network_Command_IDs--there is no network command id for flight coast

**Comment by benoiteom** [comment]
Sorry about that. Should be compiling now

**Comment by schmidtwmark** [comment]
Your tests do not pass. They look close, but they're not exactly right.

Your tests should have two parts: 

1. Transitioning to the state you want to verify
2. Ensuring that for this state, there are no faulty transitions. For example, it would be bad if we could transition from FunctionalTest to FlightAccel. We wouldn't want our pod zooming off the track if we accidentally send that transition! These tests are here to verify that a situation like that will not happen if we were to modify the state machine in any way.

**Pull request closed without merging**
