### PR TITLE
Add PRU documentation

### PR DESCRIPTION
**Pull request by rgw3d**
Literally added one link to the PRU documentation README

Magnets are weird
Hyperloop I adore
The PRU-ICSS allows for a lot of IO flexibility
Using a single core

### CODE REVIEW

**Review by schmidtwmark — CHANGES_REQUESTED** [review]
Your poem has weird rhythm, fix it

And what kind of rhyme pattern is ABCB?

**Comment by rgw3d** [comment]
Is it better now?

**Comment by schmidtwmark** [comment]
It's the third line I have issues with. It's just a little strange. Plus the rhyme is still weak

**Comment by rgw3d** [comment]
This isn't a poetry class

**Review by schmidtwmark — APPROVED** [review]

**Comment by rgw3d** [comment]
It's the "Roses are red... " style. But without the usual "Roses are red" opening because I believe it to be overused

**Pull request merged**
