### PR TITLE
Update State Test

### PR DESCRIPTION
**Pull request by mbaltman**

### CODE REVIEW

**Comment by schmidtwmark** [comment]
Your code does not compile! Once it compiles, I'll add you to slack and give you more feedback.

**Comment by mbaltman** [comment]
I updated the file, it still says it fails the tests when it compiles however it does compile and run!

**Comment by schmidtwmark** [comment]
You need to double check your transitions to ensure that the tests all pass. For example, in TEST_F(FunctionalTest), your test goes 

Safe -> Functional -> FAIL Launch_Ready -> Safe -> Loading

Safe -> Loading should fail, but you have it marked as true. Remember that running MoveState doesn't just check if the transition can occur, but actually makes the transition happen if it can occur.

Your tests should have two parts: 

1. Transitioning to the state you want to verify
2. Ensuring that for this state, there are no faulty transitions. For example, it would be bad if we could transition from FunctionalTest to FlightAccel. We wouldn't want our pod zooming off the track if we accidentally send that transition! These tests are here to verify that a situation like that will not happen if we were to modify the state machine in any way.

**Comment by schmidtwmark** [comment]
Your LaunchReady test still fails!

**Pull request closed without merging**
