### PR TITLE
Pod4 add flight plan

### PR DESCRIPTION
**Pull request by rgw3d**
Adding a configurable flight plan.

This is done via an additional configuration file, read in using the same Configuration Manager that the other config file uses. However, the data is stored slightly differently than the normal configurations.

This file ONLY CONTAINS torque throttle settings at different time stamps. That's it. no extra stuff.

I tried to make this as simple as possible, to save on programming. 

by default, it uses the `defaultFlightPlan.txt` file.

### CODE REVIEW

**Comment by anshulshah957** [comment]
Reading through it looks fine, and the test works. Still have to check it on BBB

**Review by anshulshah957 — APPROVED** [review]

**Review by epaglier — APPROVED** [review]
Reading through your code I believe it looks good. I haven't had the chance to run it yet, I will be able to do that tomorrow if you want to wait for that. If you feel confident with how it runs I am ok with merging it.

**Comment by epaglier** [comment]
Also, this merge will bring in a few changes to the Frontend. This shouldn't be an issue since we will have the new Frontend by the end of this week its just an FYI. Also, is the testing file at the end supposed to have the negative values and the "wow"?

**Comment by rgw3d** [comment]
> Also, this merge will bring in a few changes to the Frontend. This shouldn't be an issue since we will have the new Frontend by the end of this week its just an FYI. Also, is the testing file at the end supposed to have the negative values and the "wow"?

you mean the `/tests/test.txt ` file? Yes. It's just for testing how the Configuration parser works.

**Pull request merged**
